# Alternative: Manual build secrets approach
# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy (Manual Secrets)
on:
  # Uncomment and use this workflow if you prefer manual secret management
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Manual trigger only
jobs:
  deploy:
    name: Deploy app with manual build secrets
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # First, uncomment Option 1 in Dockerfile and comment Option 2
      - name: Deploy with build secrets
        run: |
          flyctl deploy --remote-only \
            --build-secret NEXT_PUBLIC_NAME="${{ secrets.NAME }}"

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          NAME: ${{ secrets.NAME }}
