# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy with build secrets automation
        run: |
          echo "FLY_API_TOKEN (first 10 chars): ${FLY_API_TOKEN:0:10}..."
          echo "FLY_API_TOKEN (last 10 chars): ...${FLY_API_TOKEN: -10}"
          echo "FLY_API_TOKEN length: ${#FLY_API_TOKEN}"
          
          # Login with access token
          flyctl auth login --access-token=$FLY_API_TOKEN
          
          # Deploy with console
          flyctl console --dockerfile Dockerfile.deploy -C "/srv/deploy.sh" --env=FLY_API_TOKEN=$(flyctl tokens create deploy)

        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
